sudo: required
services:
    - docker

before_install:
    - docker build -t ayush/docker-frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true ayush/docker-frontend npm run test -- --coverage